let deferredPrompt;
const API_URL = localStorage.getItem("marioApiUrl") || "";
const questions=["Tell me about your day.","What did you do yesterday?","What are your plans for tomorrow?","Describe your job in three sentences.","Tell me about your favorite food.","What is difficult for you when you speak English?","Describe a person you admire.","What would you like to do next weekend?"];
const shadows=["I want to improve my American pronunciation.","Could you say that again, please?","I usually go to work at eight.","Yesterday I worked all day and then I went home.","I feel more confident when I practice every day.","Speaking English is getting easier for me.","I would like to order a coffee, please."];
const sounds=[{title:"TH sound: think / three / thank",tip:"Pon la punta de la lengua suavemente entre los dientes y sopla. No digas “tink”.",example:"think, three, thank you"},{title:"V sound: very / voice / vacation",tip:"Toca el labio inferior con los dientes superiores y vibra. No lo pronuncies como B.",example:"very good voice"},{title:"American R: car / work / teacher",tip:"Lleva la lengua hacia atrás sin tocar el paladar.",example:"car, work, teacher"},{title:"Final ED: worked / played / wanted",tip:"Worked suena T, played suena D, wanted suena ID.",example:"worked, played, wanted"}];
const roles=[{title:"At a restaurant",line:"Mario: Hi! Are you ready to order?"},{title:"At the airport",line:"Mario: Good morning. Can I see your passport, please?"},{title:"Job interview",line:"Mario: Tell me about yourself."},{title:"At work",line:"Mario: Can you explain what you did today?"}];

document.querySelectorAll(".tabs button").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.screen).classList.add("active");}));
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;});
function installApp(){if(deferredPrompt){deferredPrompt.prompt();}else alert("En Chrome toca ⋮ y luego Agregar a pantalla principal.");}
function getText(id){return document.getElementById(id).textContent;}
function random(arr){return arr[Math.floor(Math.random()*arr.length)];}
function marioSpeak(text,rate=.9){if(!("speechSynthesis" in window)){alert("Este navegador no permite voz.");return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=rate;u.pitch=1;const voices=speechSynthesis.getVoices();const us=voices.find(v=>v.lang==="en-US")||voices.find(v=>v.lang&&v.lang.startsWith("en"));if(us)u.voice=us;speechSynthesis.speak(u);}
function listenTo(id){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Tu navegador no permite reconocimiento de voz. Escribe tu respuesta.");return;}const rec=new SR();rec.lang="en-US";rec.interimResults=false;rec.continuous=false;rec.onresult=e=>{document.getElementById(id).value=Array.from(e.results).map(r=>r[0].transcript).join(" ");};rec.onerror=e=>alert("Error de micrófono: "+e.error);rec.start();}
function newQuestion(){document.getElementById("question").textContent=random(questions);}
function newShadow(){document.getElementById("shadowPhrase").textContent=random(shadows);}
function newSound(){const s=random(sounds);document.getElementById("soundTitle").textContent=s.title;document.getElementById("soundTip").textContent=s.tip;}
function speakSound(){const title=getText("soundTitle");const s=sounds.find(x=>x.title===title)||sounds[0];marioSpeak(s.example,.75);}
function newRole(){const r=random(roles);document.getElementById("roleTitle").textContent=r.title;document.getElementById("roleLine").textContent=r.line;}
function correctSpeaking(){localCorrect("answer","feedback",getText("question"));}
function correctRole(){localCorrect("roleAnswer","roleFeedback",getText("roleLine"));}
function sendChat(){const input=document.getElementById("chatInput");const text=input.value.trim();if(!text)return;addBubble("user","<b>You:</b> "+escapeHtml(text));input.value="";const response=buildMarioResponse(text);addBubble("mario","<b>Mario:</b> "+response.reply);addBubble("feedback-bubble","<b>Correction:</b><br>"+response.feedback);marioSpeak(response.spoken);addProgress(text.split(/\s+/).length,response.score,20);}
function addBubble(type,html){const chat=document.getElementById("chat");const div=document.createElement("div");div.className="bubble "+type;div.innerHTML=html;chat.appendChild(div);chat.scrollTop=chat.scrollHeight;}
function buildMarioResponse(text){let improved=text;let notes=[];const rules=[[/I go to (.+) yesterday/ig,"I went to $1 yesterday","Use Simple Past with yesterday."],[/I have (\d+) years old/ig,"I am $1 years old","Say: I am 45 years old."],[/I am agree/ig,"I agree","Do not say I am agree."],[/people is/ig,"people are","People is plural."],[/I am work/ig,"I work","Say: I work, not I am work."]];rules.forEach(([re,rep,note])=>{if(re.test(improved)){improved=improved.replace(re,rep);notes.push(note);}});const score=Math.max(60,Math.min(98,78+Math.floor(text.split(/\s+/).length/3)-notes.length*4));return{reply:"Good job. Now try to say it again with better rhythm. My next question is: What are your plans for tomorrow?",spoken:"Good job. Now try to say it again with better rhythm. What are your plans for tomorrow?",feedback:`Natural version: <b>${escapeHtml(improved)}</b><br>${notes.length?notes.join("<br>"):"Your answer is good for B1. Try to speak in complete sentences."}<br>Score: <b>${score}/100</b>`,score};}
function localCorrect(inputId,outputId,prompt){const text=document.getElementById(inputId).value.trim();if(!text){document.getElementById(outputId).innerHTML="Primero habla o escribe una respuesta.";return;}const r=buildMarioResponse(text);addProgress(text.split(/\s+/).length,r.score,15);document.getElementById(outputId).innerHTML=`<b>Pregunta:</b><br>${escapeHtml(prompt)}<br><br>${r.feedback}<br><button onclick="marioSpeak('${text.replace(/'/g,"\\'")}')">🔊 Escuchar tu frase</button>`;}
function checkShadow(){const target=getText("shadowPhrase").toLowerCase().replace(/[^a-z\s]/g,"").trim();const ans=document.getElementById("shadowAnswer").value.toLowerCase().replace(/[^a-z\s]/g,"").trim();if(!ans){document.getElementById("shadowFeedback").innerHTML="Primero repite la frase.";return;}const tw=target.split(/\s+/),aw=ans.split(/\s+/);const hits=tw.filter(w=>aw.includes(w)).length;const score=Math.round(hits/tw.length*100);addProgress(aw.length,score,10);document.getElementById("shadowFeedback").innerHTML=`<b>Coincidencia:</b> ${score}%<br><b>Frase correcta:</b> ${getText("shadowPhrase")}<br>Ahora repítela copiando ritmo y entonación.`;}
function loadProgress(){return JSON.parse(localStorage.getItem("marioV6")||'{"xp":0,"sessions":0,"words":0,"scores":[],"lastDay":"","streak":0}');}
function saveProgress(p){localStorage.setItem("marioV6",JSON.stringify(p));updateStats();}
function addProgress(words,score,xp){const p=loadProgress();const today=new Date().toDateString();if(p.lastDay!==today){p.streak=(p.lastDay?p.streak+1:1);p.lastDay=today;}p.sessions++;p.words+=words;p.scores.push(score);p.xp+=xp;saveProgress(p);}
function updateStats(){const p=loadProgress();const avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;document.getElementById("xp").textContent=p.xp;document.getElementById("streak").textContent=p.streak;document.getElementById("sessions").textContent=p.sessions;document.getElementById("avg").textContent=avg;}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{});}
updateStats();
