let deferredPrompt;
const questions=["Tell me about your day.","What did you do yesterday?","What are your plans for tomorrow?","Describe your job in three sentences.","Tell me about your favorite food.","What is difficult for you when you speak English?","Describe a person you admire.","What would you like to do next weekend?","Tell me about a place you want to visit.","What do you usually do in the morning?"];
const shadows=["I want to improve my American pronunciation.","Could you say that again, please?","I usually go to work at eight.","Yesterday I worked all day and then I went home.","I feel more confident when I practice every day.","Speaking English is getting easier for me.","I would like to order a coffee, please.","Can you help me with this problem?"];
const sounds=[{title:"TH sound: think / three / thank",tip:"Pon la punta de la lengua suavemente entre los dientes y sopla. No digas “tink”.",example:"think, three, thank you"},{title:"V sound: very / voice / vacation",tip:"Toca el labio inferior con los dientes superiores y vibra. No lo pronuncies como B.",example:"very good voice"},{title:"American R: car / work / teacher",tip:"Lleva la lengua hacia atrás sin tocar el paladar.",example:"car, work, teacher"},{title:"Final ED: worked / played / wanted",tip:"Worked suena T, played suena D, wanted suena ID.",example:"worked, played, wanted"},{title:"Schwa sound: about / today / support",tip:"La vocal débil suena como 'uh'. Es muy común en inglés americano.",example:"about today support"}];
const roles=[{title:"At a restaurant",line:"Mario: Hi! Are you ready to order?"},{title:"At the airport",line:"Mario: Good morning. Can I see your passport, please?"},{title:"Job interview",line:"Mario: Tell me about yourself."},{title:"At work",line:"Mario: Can you explain what you did today?"},{title:"At a hotel",line:"Mario: Welcome! Do you have a reservation?"}];

document.querySelectorAll(".tabs button").forEach(btn=>{btn.addEventListener("click",()=>{document.querySelectorAll(".tabs button").forEach(b=>b.classList.remove("active"));document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));btn.classList.add("active");document.getElementById(btn.dataset.screen).classList.add("active");});});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;});
function installApp(){if(deferredPrompt){deferredPrompt.prompt();}else alert("En Chrome toca ⋮ y luego Agregar a pantalla principal.");}
function getText(id){return document.getElementById(id).textContent;}
function random(arr){return arr[Math.floor(Math.random()*arr.length)];}
function marioSpeak(text,rate=.9){if(!("speechSynthesis" in window)){alert("Este navegador no permite voz.");return;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=rate;u.pitch=1;const voices=speechSynthesis.getVoices();const us=voices.find(v=>v.lang==="en-US")||voices.find(v=>v.lang&&v.lang.startsWith("en"));if(us)u.voice=us;speechSynthesis.speak(u);}
function listenTo(id){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Tu navegador no permite reconocimiento de voz. Escribe tu respuesta.");return;}const rec=new SR();rec.lang="en-US";rec.interimResults=false;rec.continuous=false;rec.onresult=e=>{document.getElementById(id).value=Array.from(e.results).map(r=>r[0].transcript).join(" ");};rec.onerror=e=>alert("Error de micrófono: "+e.error);rec.start();}
function newQuestion(){document.getElementById("question").textContent=random(questions);}
function newShadow(){document.getElementById("shadowPhrase").textContent=random(shadows);}
function newSound(){const s=random(sounds);document.getElementById("soundTitle").textContent=s.title;document.getElementById("soundTip").textContent=s.tip;}
function speakSound(){const title=getText("soundTitle");const s=sounds.find(x=>x.title===title)||sounds[0];marioSpeak(s.example,.75);}
function newRole(){const r=random(roles);document.getElementById("roleTitle").textContent=r.title;document.getElementById("roleLine").textContent=r.line;}
function correctSpeaking(){localCorrect("answer","feedback",getText("question"));}
function correctRole(){localCorrect("roleAnswer","roleFeedback",getText("roleLine"));}
function localCorrect(inputId,outputId,prompt){const text=document.getElementById(inputId).value.trim();if(!text){document.getElementById(outputId).innerHTML="Primero habla o escribe una respuesta.";return;}let improved=text;let notes=[];const rules=[[/I go to (.+) yesterday/ig,"I went to $1 yesterday","Con yesterday usamos Simple Past: went, worked, studied."],[/I have (\d+) years old/ig,"I am $1 years old","En inglés la edad se dice con BE: I am 45 years old."],[/I am agree/ig,"I agree","No se dice I am agree. Se dice I agree."],[/people is/ig,"people are","People es plural."],[/I am work/ig,"I work","Para hablar de tu trabajo usa I work."],[/I no /ig,"I don't ","Para negar en presente usa don't."]];rules.forEach(([re,rep,note])=>{if(re.test(improved)){improved=improved.replace(re,rep);notes.push(note);}});const words=text.split(/\s+/).filter(Boolean).length;const score=Math.max(60,Math.min(98,76+Math.floor(words/3)-notes.length*3));addProgress(words,score,15);document.getElementById(outputId).innerHTML=`<b>Pregunta:</b><br>${escapeHtml(prompt)}<br><br><b>Tu respuesta:</b><br>${escapeHtml(text)}<br><br><b>Versión más natural:</b><br>${escapeHtml(improved)}<br><br><b>Explicación:</b><br>${notes.length?notes.join("<br>"):"Muy bien para B1. Ahora intenta hablar con más ritmo, conectar palabras y usar frases completas."}<br><br><b>Pronunciación americana:</b><br>No pronuncies palabra por palabra. Une sonidos y marca las palabras importantes.<br><br><b>Puntaje aproximado:</b> ${score}/100<br><button onclick="marioSpeak('${improved.replace(/'/g,"\\'")}')">🔊 Escuchar versión correcta</button>`;}
function checkShadow(){const target=getText("shadowPhrase").toLowerCase().replace(/[^a-z\s]/g,"").trim();const ans=document.getElementById("shadowAnswer").value.toLowerCase().replace(/[^a-z\s]/g,"").trim();if(!ans){document.getElementById("shadowFeedback").innerHTML="Primero repite la frase.";return;}const tw=target.split(/\s+/),aw=ans.split(/\s+/);const hits=tw.filter(w=>aw.includes(w)).length;const score=Math.round(hits/tw.length*100);addProgress(aw.length,score,10);document.getElementById("shadowFeedback").innerHTML=`<b>Coincidencia:</b> ${score}%<br><b>Frase correcta:</b> ${getText("shadowPhrase")}<br>Ahora repítela copiando ritmo y entonación.`;}
function completeDaily(){addProgress(20,90,25);alert("¡Práctica diaria completada! +25 XP");}
function loadProgress(){return JSON.parse(localStorage.getItem("marioV5")||'{"xp":0,"sessions":0,"words":0,"scores":[],"lastDay":"","streak":0}');}
function saveProgress(p){localStorage.setItem("marioV5",JSON.stringify(p));updateStats();}
function addProgress(words,score,xp){const p=loadProgress();const today=new Date().toDateString();if(p.lastDay!==today){p.streak=(p.lastDay?p.streak+1:1);p.lastDay=today;}p.sessions++;p.words+=words;p.scores.push(score);p.xp+=xp;saveProgress(p);}
function updateStats(){const p=loadProgress();const avg=p.scores.length?Math.round(p.scores.reduce((a,b)=>a+b,0)/p.scores.length):0;document.getElementById("xp").textContent=p.xp;document.getElementById("streak").textContent=p.streak;document.getElementById("sessions").textContent=p.sessions;document.getElementById("avg").textContent=avg;}
function escapeHtml(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));}
if("serviceWorker" in navigator){navigator.serviceWorker.register("sw.js").catch(()=>{});}
updateStats();